version: '3'
services:
  openalpr:
    build: .
    container_name: openalpr
    ports:
      - "6080:80"
    volumes:
      - app-volume:/home/desktop
      - .:/home/dashcam
      - /opt/intel/openvino:/opt/intel/openvino
volumes:
  app-volume: